log_level: DEBUG
search_concurrency: 1
search_rate: 1
token_ttl: 1h
words_address: localhost:28081
update_address: localhost:28082
search_address: localhost:28083
api_server:
  address: localhost:8080
  timeout: 5s
cors_allowed_origins:
  - http://localhost:5173
  - http://localhost
  - http://144.31.170.129
