services:

  api:
    image: api:latest
    build:
      context: search-services
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    ports:
      - 28080:8080
    volumes:
      - ./search-services/api/config.yaml:/config.yaml
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=password
      - TOKEN_TTL=1h
      - API_ADDRESS=:8080
      - WORDS_ADDRESS=words:8080
      - UPDATE_ADDRESS=update:8080
      - SEARCH_ADDRESS=search:8080
      - SEARCH_CONCURRENCY=10
      - SEARCH_RATE=100
    depends_on:
      - words
      - update
      - search

  words:
    image: words:latest
    build:
      context: search-services
      dockerfile: Dockerfile.words
    container_name: words
    restart: unless-stopped
    ports:
      - 28081:8080
    volumes:
      - ./search-services/words/config.yaml:/config.yaml
    environment:
      - WORDS_ADDRESS=:8080

  update:
    image: update:latest
    build:
      context: search-services
      dockerfile: Dockerfile.update
    container_name: update
    restart: unless-stopped
    ports:
      - 28082:8080
    volumes:
      - ./search-services/update/config.yaml:/config.yaml
    environment:
      - UPDATE_ADDRESS=:8080
      - DB_ADDRESS=postgres://postgres:password@postgres:5432/postgres
      - XKCD_URL=https://xkcd.com
      - XKCD_CONCURRENCY=10
      - WORDS_ADDRESS=words:8080
      - BROKER_ADDRESS=nats://nats:4222
      - MINIO_CONNECT_ADDRESS=minio:9000
      - MINIO_PUBLIC_ADDRESS=localhost:9000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      words:
        condition: service_started
      nats:
        condition: service_started

  tests:
    image: tests:latest
    build: tests
    container_name: tests
    restart: "no"
    entrypoint: "true"

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  search:
    image: search:latest
    build:
      context: search-services
      dockerfile: Dockerfile.search
    container_name: search
    restart: unless-stopped
    ports:
      - 28083:8080
    volumes:
      - ./search-services/search/config.yaml:/config.yaml
    environment:
      - SEARCH_ADDRESS=:8080
      - DB_ADDRESS=postgres://postgres:password@postgres:5432/postgres
      - WORDS_ADDRESS=words:8080
      - SEARCH_RATE=100
      - SEARCH_CONCURRENCY=10
      - BROKER_ADDRESS=nats://nats:4222
    depends_on:
      postgres:
        condition: service_healthy
      words:
        condition: service_started
      nats:
        condition: service_started

  categorizer:
    image: categorizer:latest
    build:
      context: search-services
      dockerfile: Dockerfile.categorizer
    container_name: categorizer
    restart: unless-stopped
    ports:
      - 28084:8080
    volumes:
      - ./search-services/categorizer/config.yaml:/config.yaml
    environment:
      - CATEGORIZER_ADDRESS=:8080
      - OLLAMA_URL=http://ollama:11434
      - CONCURRENCY=10
      - BROKER_ADDRESS=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
      ollama:
        condition: service_healthy

  ollama:
    image: my-ollama:latest
    build: 
      context: search-services
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - 11435:11434
    environment:
      - OLLAMA_MODEL=phi3:mini
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "18888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  nats:
    image: nats
    ports:
      - "4222:4222"
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root 
      MINIO_ROOT_PASSWORD: password 
      MINIO_USE_SSL: "false"
      MINIO_DEFAULT_BUCKETS: "images"
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  initminio:
    image: minio/mc:latest
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 root password;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set download myminio/images;
      echo 'all done';
      exit 0;
      "


volumes:
  postgres:
  pgadmin:
  minio-storage:
  ollama_data:
