FROM ollama/ollama:latest

# RUN apk add --no-cache curl bash
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*
# Создаём entrypoint скрипт прямо в Dockerfile
RUN mkdir -p /app-entrypoint && \
    printf '#!/bin/bash\n' > /app-entrypoint/entrypoint.sh && \
    printf '\nollama serve &\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'PID=$!\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'echo "Waiting for Ollama API..."\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'until curl -s http://localhost:11434/api/tags > /dev/null; do sleep 2; done\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'echo "Ollama API is up."\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'ollama pull "$OLLAMA_MODEL"\n' >> /app-entrypoint/entrypoint.sh && \
    printf 'wait $PID\n' >> /app-entrypoint/entrypoint.sh && \
    chmod +x /app-entrypoint/entrypoint.sh

ENV OLLAMA_MODEL=phi3:mini

ENTRYPOINT ["/app-entrypoint/entrypoint.sh"]
