log_level: DEBUG
update_address: localhost:28082
words_address: localhost:28081
db_address: postgres://postgres:password@localhost:5432/postgres
broker_address: nats://localhost:4222
xkcd:
  url: https://xkcd.com
  concurrency: 10
  timeout: 10s
  schedule: "0 9 * * 1,3,5" # mon, wed, fri at 09:00
