log_level: DEBUG
update_address: localhost:28082
words_address: localhost:28081
db_address: postgres://postgres:password@localhost:5432/postgres
broker_address: nats://localhost:4222
xkcd:
  url: https://xkcd.com
  concurrency: 10
  check_period: 1h
  timeout: 10s
